# Generated by Django 2.0.2 on 2018-06-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_info_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['first_name'], 'permissions': (('can_view_records', 'View Patient List'),)},
        ),
    ]
