# Generated by Django 2.0.2 on 2018-06-23 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_auto_20180620_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Checklistitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a check list item (Eg. Initials, Medication, Vitamins)', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist',
            field=models.ManyToManyField(help_text='Select a check list item(s) for this patient', to='patients.Checklistitems'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
