# Generated by Django 2.0.2 on 2018-06-24 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20180622_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_name', to='patients.Info'),
        ),
    ]
