# Generated by Django 2.0.2 on 2018-06-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20180624_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='checklist',
        ),
        migrations.AddField(
            model_name='checklist',
            name='allergies',
            field=models.BooleanField(default='False', verbose_name='Ask about Allergies'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='initialized',
            field=models.BooleanField(default='False', verbose_name='Initial Visit'),
        ),
    ]
