# Generated by Django 2.0.2 on 2018-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20180624_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='initialized',
        ),
        migrations.AddField(
            model_name='checklist',
            name='conditions',
            field=models.BooleanField(default=False, verbose_name='Ask about any pre-existing conditions'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='dexar',
            field=models.BooleanField(default=False, verbose_name='Dexar'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='logging',
            field=models.BooleanField(default=False, verbose_name='Discuss Importance of Logging'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='medications',
            field=models.BooleanField(default=False, verbose_name='Ask about current Medications'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='supplements',
            field=models.BooleanField(default=False, verbose_name='Ask about current vitamin/mineral supplementation'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='weight',
            field=models.BooleanField(default=False, verbose_name='Weigh In'),
        ),
    ]
