# Generated by Django 2.0.2 on 2018-06-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20180625_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a branch office name', max_length=150, verbose_name='Branch Name')),
            ],
        ),
        migrations.AddField(
            model_name='initial',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='f', help_text='Gender', max_length=1),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='bp_diastolic',
            field=models.PositiveIntegerField(help_text='Enter BP(Diastolic)', null=True, verbose_name='BP Diastolic'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='bp_systolic',
            field=models.PositiveIntegerField(help_text='Enter BP(Systolic)', null=True, verbose_name='BP Systolic'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='date_biometric',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Biometric'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Day', verbose_name='Select Day'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='vat',
            field=models.FloatField(blank=True, help_text='Enter VAT', null=True, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='info',
            name='initial',
            field=models.OneToOneField(blank=True, help_text='Select an initial patient', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Initial', verbose_name='Select Initial Patient'),
        ),
        migrations.AlterField(
            model_name='info',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='info',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Branch', verbose_name='Branch Name'),
        ),
    ]
