# Generated by Django 2.0.2 on 2018-06-27 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0010_auto_20180625_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(help_text='Enter a preferred name to use', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Enter any notes on patient here', null=True)),
                ('phone', models.CharField(help_text='Enter a mobile number', max_length=100)),
                ('height', models.FloatField(help_text='Enter height in inches')),
                ('profile_pic', models.FileField(blank=True, upload_to='profile_pics', verbose_name='Profile Picture')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='f', help_text='Gender', max_length=1)),
                ('address1', models.CharField(blank=True, help_text='Enter Street Address', max_length=100, null=True)),
                ('address2', models.CharField(blank=True, help_text='Enter Additional Address Here', max_length=100, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Branch', verbose_name='Branch Name')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Country')),
                ('ethnicity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Ethnicity')),
                ('initial', models.OneToOneField(blank=True, help_text='Select an initial patient', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Initial', verbose_name='Select Initial Patient')),
                ('insurance', models.ManyToManyField(help_text='Select an insurance for this patient', to='patients.Insurance')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'permissions': (('can_view_records', 'View Patient List'),),
            },
        ),
    ]
