# Generated by Django 2.0.2 on 2018-06-28 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20180627_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter patient first name', max_length=30, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Enter patient last name', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Enter patient middle name', max_length=30, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometrics', to='patients.Profile'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_name', to='patients.Profile'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='patients.Profile'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='patients.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(help_text='Enter height in inches', verbose_name='Height in inches'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insurance',
            field=models.ManyToManyField(help_text='Select an insurance for this patient', to='patients.Insurance', verbose_name='Select Insurance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter any notes on patient here', null=True, verbose_name='Enter Notes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='Enter a mobile number', max_length=100, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(help_text='Enter a preferred name to use', max_length=100, verbose_name='Preferred Name'),
        ),
        migrations.AlterField(
            model_name='week',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeks', to='patients.Profile'),
        ),
    ]
