# Generated by Django 2.0.2 on 2018-06-28 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20180628_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an Exercise Plan (Eg. Resistance, HIIT,etc)', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='dexar',
        ),
        migrations.AddField(
            model_name='checklist',
            name='date_checklist',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Checklist'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='dexa',
            field=models.BooleanField(default=False, verbose_name='Dexa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_join',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='allergen',
            field=models.ManyToManyField(help_text='Select an Allergen for this patient', to='patients.Allergen', verbose_name='Select Allergen'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='date_allergy',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Record'),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='date_biometric',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Biometric'),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='date_diagnose',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='illness',
            field=models.ManyToManyField(help_text='Select an illness for this patient', to='patients.Illness', verbose_name='Select Illness'),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='initial',
            name='date_initial',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Initial Visit'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='date_lab',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Lab'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='test',
            field=models.ManyToManyField(help_text='Select a test for this patient', to='patients.Test', verbose_name='Select Test'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='value',
            field=models.CharField(blank=True, help_text='Enter test result', max_length=100, null=True, verbose_name='Test Result'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date_meal',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Meal Plan'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Plan', verbose_name='Select Meal Plan'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='date_end',
            field=models.DateField(blank=True, help_text='Enter date medication discontinued', null=True, verbose_name='Date Medication Ended'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='date_medication',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Med Record Date'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='date_start',
            field=models.DateField(blank=True, help_text='Enter date medication started', null=True, verbose_name='Date Medication Started'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dose',
            field=models.FloatField(help_text='Enter dosage', null=True, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='drug',
            field=models.ManyToManyField(help_text='Select a drug for this patient', to='patients.Drug', verbose_name='Select Drug'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.PositiveIntegerField(help_text='Enter frequency of medication use per day', null=True, verbose_name='Frequency of use per day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='ab_discomfort',
            field=models.BooleanField(default=False, help_text='Ab Discomfort?', verbose_name='Abdominal Discomfort?'),
        ),
        migrations.AlterField(
            model_name='week',
            name='bp_diastolic',
            field=models.PositiveIntegerField(blank=True, help_text='Enter Diastolic Blood Pressure', null=True, verbose_name='BP Diastolic'),
        ),
        migrations.AlterField(
            model_name='week',
            name='bp_systolic',
            field=models.PositiveIntegerField(blank=True, help_text='Enter Systolic Blood Pressure', null=True, verbose_name='BP Systolic'),
        ),
        migrations.AlterField(
            model_name='week',
            name='broth',
            field=models.PositiveIntegerField(blank=True, help_text='Enter number of broths per day', null=True, verbose_name='Broths per day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='commentary',
            field=models.TextField(blank=True, help_text='Commentaries/Orders', null=True, verbose_name='Commentaries/Orders'),
        ),
        migrations.AlterField(
            model_name='week',
            name='concerns',
            field=models.TextField(blank=True, help_text='Enter any concerns', null=True, verbose_name='Enter any Concerns'),
        ),
        migrations.AlterField(
            model_name='week',
            name='constipation',
            field=models.BooleanField(default=False, help_text='Constipation?', verbose_name='Constipation?'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date_menstruation',
            field=models.DateField(blank=True, help_text='Enter last menstruation if applicable', null=True, verbose_name='Last Menstruation (if applicable)'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date_week',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Record'),
        ),
        migrations.AlterField(
            model_name='week',
            name='delta',
            field=models.FloatField(blank=True, help_text='Enter weekly weight change (Delta)', null=True, verbose_name='Delta Weight Change'),
        ),
        migrations.AlterField(
            model_name='week',
            name='diarrhea',
            field=models.BooleanField(default=False, help_text='Diarrhea?', verbose_name='Diarrhea?'),
        ),
        migrations.AlterField(
            model_name='week',
            name='dizziness',
            field=models.BooleanField(default=False, help_text='Dizziness?', verbose_name='Dizziness?'),
        ),
        migrations.AlterField(
            model_name='week',
            name='eating_off',
            field=models.BooleanField(default=False, help_text='Eating off?', verbose_name='Eating Off?'),
        ),
        migrations.AlterField(
            model_name='week',
            name='exercise',
            field=models.ManyToManyField(help_text='Select exercises for this patient', to='patients.Exercise', verbose_name='Exercises for patient'),
        ),
        migrations.AlterField(
            model_name='week',
            name='fluid',
            field=models.FloatField(blank=True, help_text='Enter fluid ounces per day', null=True, verbose_name='Fluid Ounces per day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='gas_bloating',
            field=models.BooleanField(default=False, help_text='Gas/Bloating?', verbose_name='Gas/Bloating?'),
        ),
        migrations.AlterField(
            model_name='week',
            name='headache',
            field=models.BooleanField(default=False, help_text='Headache?', verbose_name='Headache?'),
        ),
        migrations.AlterField(
            model_name='week',
            name='medication',
            field=models.BooleanField(default=False, help_text='Change in medication?(if yes, use med list)', verbose_name='Change in medication?'),
        ),
        migrations.AlterField(
            model_name='week',
            name='nausea',
            field=models.BooleanField(default=False, help_text='Nausea?', verbose_name='Nausea?'),
        ),
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Enter Week Number', null=True, verbose_name='Week Number'),
        ),
        migrations.AlterField(
            model_name='week',
            name='o2',
            field=models.PositiveIntegerField(blank=True, help_text='Enter O2', null=True, verbose_name='O2'),
        ),
        migrations.AlterField(
            model_name='week',
            name='pulse',
            field=models.PositiveIntegerField(blank=True, help_text='Enter Pulse', null=True, verbose_name='Pulse Rate'),
        ),
        migrations.AlterField(
            model_name='week',
            name='sigma',
            field=models.FloatField(blank=True, help_text='Enter total weight change (Sigma)', null=True, verbose_name='Total Weight Change'),
        ),
        migrations.AlterField(
            model_name='week',
            name='sleep',
            field=models.CharField(blank=True, choices=[('3', 'Excellent'), ('2', 'Good'), ('1', 'Fair'), ('0', 'Poor')], default='g', help_text='Choose Sleep Quality', max_length=1, verbose_name='Select Sleep Quality'),
        ),
        migrations.AlterField(
            model_name='week',
            name='steps',
            field=models.PositiveIntegerField(blank=True, help_text='Enter number of steps', null=True, verbose_name='Number of Steps'),
        ),
        migrations.AlterField(
            model_name='week',
            name='stress',
            field=models.CharField(blank=True, choices=[('3', 'High'), ('2', 'Medium'), ('1', 'Mild'), ('0', 'None')], default='m', help_text='Choose Stress Level', max_length=1, verbose_name='Stress Level'),
        ),
        migrations.AlterField(
            model_name='week',
            name='vomiting',
            field=models.BooleanField(default=False, help_text='Vomiting?', verbose_name='Vomiting?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Programtype', verbose_name='Transform Program'),
        ),
    ]
