# Generated by Django 2.0.2 on 2018-06-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_auto_20180628_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['first_name'], 'permissions': (('can_view_records', 'View Patient List'),)},
        ),
    ]
