# Generated by Django 2.0.2 on 2018-06-28 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20180628_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='appointment',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Next Appointment'),
        ),
    ]
