# Generated by Django 2.0.2 on 2018-06-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_auto_20180628_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, help_text='Enter height in inches', null=True, verbose_name='Height in inches'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Enter patient last name', max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Enter patient middle name', max_length=30, null=True, verbose_name='Middle Name'),
        ),
    ]
