# Generated by Django 2.0.2 on 2018-06-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20180628_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['pfirst_name'], 'permissions': (('can_view_records', 'View Patient List'),)},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='pfirst_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='plast_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='middle_name',
            new_name='pmiddle_name',
        ),
    ]
