# Generated by Django 2.0.2 on 2018-07-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_auto_20180629_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='ab_discomfort_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes on Ab Discomfort'),
        ),
        migrations.AddField(
            model_name='week',
            name='constipation_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes on Constipation'),
        ),
        migrations.AddField(
            model_name='week',
            name='diarrhea_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes on Diarrhea'),
        ),
        migrations.AddField(
            model_name='week',
            name='dizziness_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes on Dizziness'),
        ),
        migrations.AddField(
            model_name='week',
            name='eating_off_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes on Eating Off'),
        ),
        migrations.AddField(
            model_name='week',
            name='fatigue_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes on Fatigue'),
        ),
        migrations.AddField(
            model_name='week',
            name='gas_bloating_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes on Gas/Bloating'),
        ),
        migrations.AddField(
            model_name='week',
            name='headache_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes on Headache'),
        ),
        migrations.AddField(
            model_name='week',
            name='nausea_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes on Nausea'),
        ),
        migrations.AddField(
            model_name='week',
            name='vomiting_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes on Vomiting'),
        ),
    ]
