# Generated by Django 2.0.2 on 2018-07-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('patients', '0025_auto_20180702_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='info',
            name='country',
        ),
        migrations.RemoveField(
            model_name='info',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='info',
            name='initial',
        ),
        migrations.RemoveField(
            model_name='info',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='state',
        ),
        migrations.RemoveField(
            model_name='info',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
